# SPDX-FileCopyrightText: Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

add_subdirectory(axpy)
#add_subdirectory(dequant)
#add_subdirectory(elementwise_mul)
#add_subdirectory(elementwise_add)
#add_subdirectory(gelu)
#add_subdirectory(gemm)
#add_subdirectory(layer_norm)
#add_subdirectory(leaky_relu)
#add_subdirectory(matrix_vector_mul)
#add_subdirectory(mem_copy)
#add_subdirectory(relu)
#add_subdirectory(rms_norm)
#add_subdirectory(rope)
#add_subdirectory(softmax)
#add_subdirectory(silu)
#add_subdirectory(swiglu)
#add_subdirectory(transpose)
#
#if (IRONCLAD_AIE_TARGET STREQUAL "aie2p")
#  add_subdirectory(mha)
#endif ()